### ISSUE TITLE
Error, too many pending metadata updates

### ISSUE THREAD

**Issue by derekatkins** [owntone/owntone-server#1357]
I set up shairport-sync in front of owntone to try to drive my whole house system.  I got it working if I have metadata turned off, but if I turn ON metadata I seem to get a bunch of errors in the log:
```
Nov 28 09:54:21 owntone owntone[3380]: [2021-11-28 09:54:21] [  LOG]   player: Error, too many pending metadata updates
Nov 28 09:54:21 owntone owntone[3380]: [2021-11-28 09:54:21] [  LOG]   player: Error, too many pending metadata updates
Nov 28 09:54:21 owntone owntone[3380]: [2021-11-28 09:54:21] [  LOG]   player: Error, too many pending metadata updates
Nov 28 09:54:22 owntone owntone[3380]: [2021-11-28 09:54:22] [  LOG]   player: Error, too many pending metadata updates
Nov 28 10:03:43 owntone owntone[6053]: [2021-11-28 10:03:43] [  LOG]   player: Error, too many pending metadata updates
Nov 28 10:03:43 owntone owntone[6053]: [2021-11-28 10:03:43] [  LOG]   player: Error, too many pending metadata updates
```
... and play seems not to go.   then owntone gets stuck.  I WAS playing with the volume, but that shouldn't make a difference, right?

I've been trying to figure out the order-of-operations to get shairport and owntone (and my Mac driving shairport) to interact reliably, and how to get the volume up without requiring me to max the volume on the Mac.

Do I need to rm the pipe before I start shairport so it creates them?  If I don't do this it feels like I never get audio.

**Comment by derekatkins** [comment]
Music just stopped playing again, and I found this in the log:
```
Nov 28 12:44:55 owntone owntone[6053]: [2021-11-28 12:44:55] [  LOG]   player: Source is not providing sufficient data, temporarily suspending playback (deficit=265096/264600 bytes)
```
So how long will it "temporarily" suspend the play?

**Comment by ejurgensen** [comment]
I assume this error is coming from using a metadata pipe?

> I WAS playing with the volume, but that shouldn't make a difference, right?

Correct. Volume changes aren't treated as metadata. Metadata in this context would mean track info, progress or artwork. The error indicates that such updates are coming faster than OwnTone was designed for. I don't understand why playback would be affected by this.

> Do I need to rm the pipe before I start shairport so it creates them?

I have mine permanently in the library.

> So how long will it "temporarily" suspend the play?

Until there is sufficient new data to play (a few seconds worth of audio). OwnTone is reading from the pipe as much as it can, trying to fill an internal buffer. If insufficient data is being written (needs to be at least 44100 x 2 x 2 bytes per second) then at some point there will be an underrun, and you will see that message in the log. Note that the message will of course also appear just when you stop or pause playback on the source.

**Comment by derekatkins** [comment]
Hi,
> I assume this error is coming from using a metadata pipe?

Yes, I did have the metadata pipe running at the time.   I was playing with it (on and off from shairport-sync) but it was on at this point in time.

> > I WAS playing with the volume, but that shouldn't make a difference, right?
> 
> Correct. Volume changes aren't treated as metadata. Metadata in this context would mean track info, progress or artwork. The error indicates that such updates are coming faster than OwnTone was designed for. I don't understand why playback would be affected by this.

Interesting, because there should not have been any other metadata coming across, and I was playing with the volume slider at the time -- I wonder if shairport-sync sends volume data down the metadata pipe?  Is there a way to log what's coming across the pipe as it gets read by OT?

> > Do I need to rm the pipe before I start shairport so it creates them?
> 
> I have mine permanently in the library.

That's what I thought, but I was definitely having issues if I start OT first with those pipes in place and then start shairport.  Of course, it's not 100% reliably reproducible.  It also could have been an issue on the Mac I was using to drive shairport.   Too many opacities ;)

> > So how long will it "temporarily" suspend the play?
> 
> Until there is sufficient new data to play (a few seconds worth of audio). OwnTone is reading from the pipe as much as it can, trying to fill an internal buffer. If insufficient data is being written (needs to be at least 44100 x 2 x 2 bytes per second) then at some point there will be an underrun, and you will see that message in the log. Note that the message will of course also appear just when you stop or pause playback on the source.

I wonder if there was a "glitch" during a DHCP operation?   In this case I did not pause or stop playing (at least I am fairly sure I didn't).  It was playing fine for an hour and then it... stopped.  I was in another room at the time when it stopped, and when I came back to my computer(s) to evaluate I saw this issue.  Even though everything thought it was still playing, I had to reset it.  (Unfortunately I don't recall at this point everything I "restarted" to get it working again -- I apologize -- yesterday was a very hectic day -- although it *did* eventually work and I left it alone, and it continued working for the rest of the evening).

**Comment by derekatkins** [comment]
I don't know if it's related or not, but I just started playing with it again this morning; I did the same thing I always do:  start amazon music, play a song, go to the dropdown and send the airplay over to "whole house", and then go and adjust the volume.  I put the volume all the way up and it was way too loud; I then started sliding it softer and then OT stopped playing.  I had to restart both SP-S and OT and rm the pipes in the middle to get it to work again.  Alas, there was nothing in the logs.

**Comment by ejurgensen** [comment]
> Interesting, because there should not have been any other metadata coming across, and I was playing with the volume slider at the time -- I wonder if shairport-sync sends volume data down the metadata pipe? Is there a way to log what's coming across the pipe as it gets read by OT?

Sorry, I just now remembered that you are using release 28.2, but when I checked the code I was looking at current master. Now I checked 28.2, and for that it looks like my answer was incorrect. In both cases the volume is received via the metadata pipe. For 28.2, volume change is internally considered a metadata event, and there is a maximum on how many of those that can be buffered within a timeframe. So too many of those and you get the error above. This is changed in current master, where the volume changes arriving via the pipe are not buffered, but instead applied directly.

There is also a deadlock bug related to metadata pipes that is present in 28.2, but should be fixed in master.

With master you can also get OwnTone to log what it receives via the metadata pipe. It does, however, require that you set the log level to spam, which will mean the log gets really big, so only do it while testing.

About the playback stopping I can't say why that is happening.

**Comment by derekatkins** [comment]
> Sorry, I just now remembered that you are using release 28.2, but when I checked the code I was looking at current master. Now I checked 28.2, and for that it looks like my answer was incorrect. In both cases the volume is received via the metadata pipe, but for 28.2, volume change is internally considered a metadata event, and there is a maximum on how many of those that can be buffered within a timeframe. So too many of those and you get the error above. This is changed in current master, where the volume changes arriving via the pipe are not buffered, but instead applied directly.

Aha!  That explains it...  It happens mostly when I "slide" the volume control, which probably sends a bunch of volume-change events.  Do you know if the shairport-sync `ignore_volume_control` has any effect here?

> There is also a deadlock bug related to metadata pipes that is present in 28.2, but should be fixed in master.

Okay.

> With master you can also get OwnTone to log what it receives via the metadata pipe. It does, however, require that you set the log level to spam, which will mean the log gets really big, so only do it while testing.

Well, this is running on a VM with tons of space, so I'm not worried about log size..  But I hear you.

> About the playback stopping I can't say why that is happening.

Yeah, me either.  I'll figure it out.

Any chance for a 28.3 release soon?  ;)

**Comment by ejurgensen** [comment]
> Do you know if the shairport-sync ignore_volume_control has any effect here?

I don't remember exactly what the shairport-sync settings do, but I can see that OwnTone will ignore volume changes from the metadata pipe if shairport-sync "software volume control" is enabled.

> Any chance for a 28.3 release soon? ;)

Still some time away, but [here is a dist tarball](http://gyfgafguf.dk/temp/owntone-a55f2c6.tar.xz) with a snapshot of current master, if it helps you.

**Comment by derekatkins** [comment]
Thanks. I'll go try that.
The RPM build from git still doesn't quite work right (within mock).

**Comment by derekatkins** [comment]
Okay, just updated to that dist tarball.  The good news is that sliding the volume control doesn't cause a metadata overload and the system to go unstable!  So it's possible this issue is fixed in master.

**Comment by ejurgensen** [comment]
Ok, let's close this for now then.
