### ISSUE TITLE
Owntone gets out of sync between the local i2s and a remote speaker

### ISSUE THREAD

**Issue by gearhead** [owntone/owntone-server#1952]
If I use owntone to play a webradio, I notice that if I let it play long enough that the local i2s output and the remote speaker running shairport-sync can get out of sync. I have never noticed it when playing individual songs, it is only with a web stream playing for a fairly long time. I start to notice it after many minutes of continuous play. I reported it on shairport-sync [shairport-sync #2111](https://github.com/mikebrady/shairport-sync/issues/2111) but Mike seems to think it doesn't lie with shairport-sync because the sync starts about 0.2 and can rise to just under 2ms.

The version of owntone is built from git 'g443fb684'

It is running on a RPi3B+ running RPiOS lite 64 bit. We are using MPD as the front end to feed it a stream or a song from the mounted drive and then select outputs via owntone.

I ran it for a while today over 30 minutes continuous and the stream gets out of sync between the local i2s HiFiBerry output and the remote output shairport-sync running on another Pi 

[owntone.log](https://github.com/user-attachments/files/24177372/owntone.log)

**Comment by ejurgensen** [comment]
Peculiar that you only see this when playing web streams, since on the output side there shouldn't be any difference between playing files and streams. I can’t think of an explanation for that.

Mike is probably right that the issue isn’t with sps, because if so, sps would drift out of sync with regular Airplay speakers. I don’t suppose that is happening. I suspect OwnTone’s local playback is drifting, and OwnTone is not detecting it. As you can see from the log file (“Sync check result”), OwnTone is at intervals checking sync. I don’t remember exactly how to read the values of “Sync check result”, I’ll have to look into that.

Other than that, I would have to try to reproduce. I’m not sure what i2s is – can you elaborate?

Btw, please note that the issue template says "Remove parts of the log file that aren't relevant".

**Comment by gearhead** [comment]
I discovered it because when I am not critically listening, I am generally playing a web stream for background noise. I can try playing a playlist today and see if it misbehaves with that. Edit: I just retried it with a playlist and it will also get out of sync after a while. I just got to song 24 and went to check and I could hear a distinct out of sync. It was playing for well over an hour from a playlist of songs.

Sorry about the jargon, by 'i2s', I mean a locally attached HiFiBerry card connected on the i2s bus. It is a PCM5122 based audio D/A card. Mine is an older model, but is basically one of these without the ADC [DAC-ADC-PRO](https://www.hifiberry.com/shop/boards/hifiberry-dac-adc-pro/). I am using it as an alsa output directly.
```
card 1: sndrpihifiberry [snd_rpi_hifiberry_dacplus], device 0: HiFiBerry DAC+ Pro HiFi pcm512x-hifi-0 [HiFiBerry DAC+ Pro HiFi pcm512x-hifi-0]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
```
`{ "id": "1", "name": "Soundcard: HiFiBerry DAC+ Pro", "type": "ALSA", "selected": true, "has_password": false, "requires_auth": false, "needs_auth_key": false, "volume": 20, "format": "pcm", "supported_formats": [ "pcm" ] } ] }`

As for the removal of parts of the log, I am sorry about that. I can process it or cut it down, but did not really know what you needed. Which bits should I keep? Just a beginning and an end snippet is what I was going to send, but was unsure.

**Comment by ejurgensen** [comment]
The below lines are the sync check. sync=0 means that the card is playing at the same rate as OwnTone's clock, so that's good. sync=1 means it is ahead (playing too fast), sync=2 means behind. As you can see, sync 2 is always after sync 1 in your example, so that's also good. Means that in general the card is actually playing at the expected rate.

I see OwnTone uses ALSA's snd_pcm_avail_delay() to measure the latency. I will try to check how SPS does it.

I should mention that this stuff quickly gets pretty complicated, and I can't make any promises about how deep I can go into it.

```
[2025-12-15 17:01:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.713249, latency=-4075.946625, r2=0.493416, sync=2
[2025-12-15 17:02:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.552907, latency=-446.363546, r2=0.986258, sync=0
[2025-12-15 17:04:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.138494, latency=-118.050753, r2=0.978661, sync=0
[2025-12-15 17:06:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.505419, latency=208.472709, r2=0.984925, sync=0
[2025-12-15 17:07:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.180306, latency=547.250153, r2=0.982927, sync=1
[2025-12-15 17:09:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.806841, latency=-775.103420, r2=0.766904, sync=2
[2025-12-15 17:11:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.122178, latency=-781.788911, r2=0.978689, sync=0
[2025-12-15 17:12:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.200378, latency=-467.569811, r2=0.984725, sync=0
[2025-12-15 17:14:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.597300, latency=-141.001350, r2=0.981758, sync=0
[2025-12-15 17:16:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.577690, latency=217.448845, r2=0.983266, sync=0
[2025-12-15 17:17:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.255362, latency=559.847681, r2=0.958539, sync=1
[2025-12-15 17:19:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.659406, latency=-947.249703, r2=0.687818, sync=2
[2025-12-15 17:21:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.247291, latency=-481.986355, r2=0.977442, sync=0
[2025-12-15 17:22:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.303084, latency=-160.678458, r2=0.956529, sync=0
[2025-12-15 17:24:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.225995, latency=162.832997, r2=0.975643, sync=0
[2025-12-15 17:26:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.079538, latency=479.849769, r2=0.976076, sync=0
[2025-12-15 17:27:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.205335, latency=799.572667, r2=0.977156, sync=1
[2025-12-15 17:29:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.940516, latency=-911.580258, r2=0.739674, sync=2
[2025-12-15 17:31:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.058062, latency=-687.770969, r2=0.980989, sync=0
[2025-12-15 17:32:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=2.913537, latency=-393.553231, r2=0.984001, sync=0
[2025-12-15 17:34:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=2.998506, latency=-102.390747, r2=0.948279, sync=0
[2025-12-15 17:36:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=2.917600, latency=195.178800, r2=0.982071, sync=0
[2025-12-15 17:37:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.013915, latency=494.136958, r2=0.967088, sync=1
[2025-12-15 17:39:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-1.017726, latency=-904.388863, r2=0.800704, sync=2
[2025-12-15 17:41:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=2.990387, latency=-417.864806, r2=0.973222, sync=0
[2025-12-15 17:42:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.010783, latency=-119.324608, r2=0.971250, sync=0
[2025-12-15 17:44:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.025713, latency=186.342856, r2=0.970427, sync=0
[2025-12-15 17:46:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.025695, latency=490.272847, r2=0.972295, sync=1
[2025-12-15 17:47:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.890651, latency=-909.275326, r2=0.760624, sync=2
[2025-12-15 17:49:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.130729, latency=-650.414635, r2=0.981364, sync=0

```

**Comment by gearhead** [comment]
Thanks for looking into this. I am sure it gets complicated. It is definitely way over my head. I have 2 shairport-sync devices and they always seem to be identically timed when playing music. It is just the local alsa output that gets out over time. To re-set it, I just restart the song and it seems to be back in sync. If there is some sort of systemic change that fixes it (pipewire or whatever) let us know and we can take a look at that, but prefer to use bare alsa.

**Comment by ejurgensen** [comment]
Checked the logs again, and I can see I missed something suspicious when I first looked at them. From the below you can see that for extended periods of time, OwnTone is setting the sample rate to 44096 for the card, meaning it is removing 4 samples each second. OwnTone does this because it thinks card playback is falling behind, which is because the cards buffer is growing. But if that's a false correction, then the actual effect will be that local card playback moves ahead of shairport-sync.

Can you hear which speaker is ahead and which one is behind?

For testing sync, OwnTone can play a reguler "bip" sound, which makes it easier to hear. But I forget how to make it do that, so I will get back to you on that.

```
[2025-12-15 17:01:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.713249, latency=-4075.946625, r2=0.493416, sync=2
[2025-12-15 17:01:07] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44096 to sync ALSA device (drift=-0.713249, latency=-4075.946625)
[2025-12-15 17:02:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.552907, latency=-446.363546, r2=0.986258, sync=0
[2025-12-15 17:04:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.138494, latency=-118.050753, r2=0.978661, sync=0
[2025-12-15 17:06:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.505419, latency=208.472709, r2=0.984925, sync=0
[2025-12-15 17:07:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.180306, latency=547.250153, r2=0.982927, sync=1
[2025-12-15 17:07:47] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44100 to sync ALSA device (drift=3.180306, latency=547.250153)
[2025-12-15 17:09:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.806841, latency=-775.103420, r2=0.766904, sync=2
[2025-12-15 17:09:27] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44096 to sync ALSA device (drift=-0.806841, latency=-775.103420)
[2025-12-15 17:11:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.122178, latency=-781.788911, r2=0.978689, sync=0
[2025-12-15 17:12:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.200378, latency=-467.569811, r2=0.984725, sync=0
[2025-12-15 17:14:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.597300, latency=-141.001350, r2=0.981758, sync=0
[2025-12-15 17:16:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.577690, latency=217.448845, r2=0.983266, sync=0
[2025-12-15 17:17:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.255362, latency=559.847681, r2=0.958539, sync=1
[2025-12-15 17:17:47] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44100 to sync ALSA device (drift=3.255362, latency=559.847681)
[2025-12-15 17:19:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.659406, latency=-947.249703, r2=0.687818, sync=2
[2025-12-15 17:19:27] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44096 to sync ALSA device (drift=-0.659406, latency=-947.249703)
[2025-12-15 17:21:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.247291, latency=-481.986355, r2=0.977442, sync=0
[2025-12-15 17:22:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.303084, latency=-160.678458, r2=0.956529, sync=0
[2025-12-15 17:24:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.225995, latency=162.832997, r2=0.975643, sync=0
[2025-12-15 17:26:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.079538, latency=479.849769, r2=0.976076, sync=0
[2025-12-15 17:27:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.205335, latency=799.572667, r2=0.977156, sync=1
[2025-12-15 17:27:47] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44100 to sync ALSA device (drift=3.205335, latency=799.572667)
[2025-12-15 17:29:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.940516, latency=-911.580258, r2=0.739674, sync=2
[2025-12-15 17:29:27] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44096 to sync ALSA device (drift=-0.940516, latency=-911.580258)
[2025-12-15 17:31:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.058062, latency=-687.770969, r2=0.980989, sync=0
[2025-12-15 17:32:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=2.913537, latency=-393.553231, r2=0.984001, sync=0
[2025-12-15 17:34:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=2.998506, latency=-102.390747, r2=0.948279, sync=0
[2025-12-15 17:36:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=2.917600, latency=195.178800, r2=0.982071, sync=0
[2025-12-15 17:37:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.013915, latency=494.136958, r2=0.967088, sync=1
[2025-12-15 17:37:47] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44100 to sync ALSA device (drift=3.013915, latency=494.136958)
[2025-12-15 17:39:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-1.017726, latency=-904.388863, r2=0.800704, sync=2
[2025-12-15 17:39:27] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44096 to sync ALSA device (drift=-1.017726, latency=-904.388863)
[2025-12-15 17:41:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=2.990387, latency=-417.864806, r2=0.973222, sync=0
[2025-12-15 17:42:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.010783, latency=-119.324608, r2=0.971250, sync=0
[2025-12-15 17:44:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.025713, latency=186.342856, r2=0.970427, sync=0
[2025-12-15 17:46:07] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.025695, latency=490.272847, r2=0.972295, sync=1
[2025-12-15 17:46:07] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44100 to sync ALSA device (drift=3.025695, latency=490.272847)
[2025-12-15 17:47:47] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=-0.890651, latency=-909.275326, r2=0.760624, sync=2
[2025-12-15 17:47:47] [ INFO] [   player (2249)]   laudio: Adjusted sample rate to 44096 to sync ALSA device (drift=-0.890651, latency=-909.275326)
[2025-12-15 17:49:27] [DEBUG] [   player (2249)]   laudio: Sync check result: drift=3.130729, latency=-650.414635, r2=0.981364, sync=0


```

**Comment by keithgrider-web** [comment]
If I remember correctly, it is the Local Card gets ahead of the Shairport-Sync remote speaker, so I think you are on to it. It'll take me a while of playing to actually listen for this again. I will do it in the next few days and report back.

**Comment by ejurgensen** [comment]
To enable the sync test mode, you can edit owntone.conf and add ´timer_test = true´ in the general section (the first section). Then just start playback of anything.

**Comment by keithgrider-web** [comment]
@ejurgensen I tried that and all I get are clicks on both local and remote speakers when I add that parameter 'timer_test = true' to the general section. No music plays, just clicks. In the log, I really do not know what I am looking for, but I see nothing that looks interesting wrt timing, but I really don't know what I am looking for.

**Comment by ejurgensen** [comment]
Yes, that's the idea. The clicks make it easier to hear if the speakers are in sync, and if not, which one is ahead or behind.

**Comment by gearhead** [comment]
Ah. I did not understand what was going on. 
Well. Last night I played music for about an hour. At this point it was very clear that the local speakers (HiFi berry on alsa) were ahead of the remote shairport-sync speakers in time.

**Comment by ejurgensen** [comment]
Ok, then let's test if it's actually the sync correction that's causing the issue. To test that, add `sync_disable = true` to the `audio` section of the config file. Then restart the server and give it another go.

**Comment by gearhead** [comment]
yep, I will try it. I will not be able to until next week, though. Were you able to hear the deviation? Like I said, it is with a stream or with playing a playlist for long periods of time. After about an hour, it it pretty apparent. We are using mpd as a front end to feed a fifo to owntone. Could we be seeing this because we are sending owntone a continuous stream of data from mpd and it is not playing individual music files that we are seeing this? We defined /run/owntone/music/pipe_mpd.fifo and this is the music source that owentone sees? We defined the fifo in mpd as alsa with 44100:16:2 format.

**Comment by gearhead** [comment]
Well, I was able to do this test before I left. It was playing for about 45 minutes and still the local output was ahead of the airplay output. I was playing for about 45 minutes. I put the 'sync_disable = true' in the config.

**Comment by ErikFontanel** [comment]
I'm experiencing the same or a similar issue with drift (I'll add my comments here but let me know if you prefer me to open a new issue).

I experience it using the following scenario:
Spotify → Librespot → output to pipe → Owntone -> 2 airplay devices (sonos device and a Yamaha receiver). 

After a while music starts to drift between two Airplay devices, briefly disconnecting and connecting one of the speakers resolves the drift (or just waiting for a bit and the drift eventually resolves itself). 

I'm experiencing it both using Owntone release 29.0 and building it from source from the latest commit ([3b84ea9](https://github.com/owntone/owntone-server/commit/3b84ea91e04fbc33b76af4addc89d69a26038467))

There's nothing in the owntone logs.

I'm using RPi 3B

```
uname -a
Linux Pi 6.12.47+rpt-rpi-v8 #1 SMP PREEMPT Debian 1:6.12.47-1+rpt1 (2025-09-16) aarch64 GNU/Linux
```

with a hifiberry dac

**Comment by ejurgensen** [comment]
Interesting. In your case, is it also without drift when you play regular files?

**Comment by ejurgensen** [comment]
Can you also share the output of http://[ipaddress]:3689/api/outputs? I would like to see if the speakers are Airplay 1 or 2. If they are both the same type, then they are getting the exact same packets from OwnTone and then it's really strange.

**Comment by ejurgensen** [comment]
I've now tried to reproduce this with a setup of one RPi running OwnTone and another running shairport-sync. I had them play a radio station for a good 45 minutes. I didn't observe any drift.

I don't have an i2s, so of course it's possible that's the missing factor.

Another factor could be the particularly radio station, though it seems unlikely. The log you attached @gearhead is for playback of fifo, but your post mentions a radio station. Do you have a link to it?

**Comment by gearhead** [comment]
I don't know what kind of music you like, but I was using this radio station. I am pretty sure just about any station will do the same thing. As I posted above, this is also apparent when I am playing a playlist. My 'frontend' is MPD that is outputting to a pipe to owntone. I am running the git version of owntone r42.gf188b6d5. I am running the released 4.3.7 version of shairport-sync. 
It was pretty apparent after about 45 min to an hour of playing that the Owntone server playing on its local output (i2s/alsa) would get ahead of the remote speaker with shairport-sync playing on its own alsa/i2s output.
[WLIR](http://hydra.cdnstream.com/1552_128)

I was just testing the latest version of Owntone. It now seems to behave differently. The shairport-sync output is ahead of the local i2s/alsa output from the start of play. I will let it play a while and see how it behaves over time.

Just to be clear, the outputs as far as owntone is concerned are the Shairport-sync remote and the "Soundcard: HiFiBerry DAC+ Pro"

**Comment by ejurgensen** [comment]
> My 'frontend' is MPD that is outputting to a pipe to owntone.

I'm a bit confused - are you also playing the radio station and the playlist like this? Then I don't understand why you wrote "If I use owntone to play a webradio" in the original post.

> I was just testing the latest version of Owntone. It now seems to behave differently.

Yes, I have delayed ALSA by 0.25 secs, there was an Airplay latency buffer OwnTone wasn't accounting for. In my tests this correction gives sync with shairport-sync. If you don't get that, then either you might have a configuration of offset_ms in owntone.conf that isn't relevant any more, or the i2s is slow to start playback. In any case, it's just a changed start time, so I expect the drift issue is still there.

**Comment by gearhead** [comment]
Sorry for the confusion. I do appreciate you looking into this. 
So, If I put that radio station in the owntone UI and start playing, I get what I described earlier: The shairport-sync speaker is temporally ahead of the local output.
```
# curl -X GET "http://localhost:3689/api/queue"
{ "version": 499, "count": 1, "items": [ { "id": 2, "position": 0, "title": "...", "artist": "Webradio", "artist_sort": "Unknown artist", "album": "WLIR", "album_sort": "Unknown album", "album_artist": "Webradio", "album_artist_sort": "Unknown artist", "composer": "...", "genre": "Unknown Genre", "year": 0, "track_number": 0, "disc_number": 0, "length_ms": 0, "media_kind": "music", "data_kind": "url", "path": "http:\/\/hydra.cdnstream.com\/1552_128", "uri": "http:\/\/hydra.cdnstream.com\/1552_128", "artwork_url": "http:\/\/JackRune.local\/tmp\/art\/radio.png", "type": "mp3", "bitrate": 128, "samplerate": 44100, "channels": 2 } ] }
# curl -X GET "http://localhost:3689/api/outputs/{202481601637172}"
{ "id": "202481601637172", "name": "LivingRune", "type": "AirPlay 1", "selected": true, "has_password": false, "requires_auth": false, "needs_auth_key": false, "volume": 41, "offset_ms": 0, "format": "alac", "supported_formats": [ "alac" ] }
# curl -X GET "http://localhost:3689/api/outputs/{1}"
{ "id": "1", "name": "Soundcard: HiFiBerry DAC+ Pro", "type": "ALSA", "selected": true, "has_password": false, "requires_auth": false, "needs_auth_key": false, "volume": 18, "offset_ms": 0, "format": "pcm", "supported_formats": [ "pcm" ] }
```

**Comment by ejurgensen** [comment]
> The shairport-sync speaker is temporally ahead of the local output.

Only temporarily? Does that mean they come into sync? If so, do they stay in sync?

Btw, you can now adjust the start time in the settings (see Remotes and outputs).

**Comment by gearhead** [comment]
Hmmm, I'll have to let it play a while and see if it comes into sync... As for the start time adjustment, I do not see anything...

<img width="615" height="446" alt="Image" src="https://github.com/user-attachments/assets/73028961-aeb3-496d-a5db-3bc40340cf3d" />

**Comment by gearhead** [comment]
I let it play a while and the Shairport-sync remote speaker seemed to be ahead of the local alsa output. I poked around on the UI and could not find any way to adjust the start time adjustment. Can you direct me a bit? Or do I not have the correct current version? I am building and running the latest 'master' from git.

**Comment by ErikFontanel** [comment]
> Can you also share the output of http://[ipaddress]:3689/api/outputs? I would like to see if the speakers are Airplay 1 or 2. If they are both the same type, then they are getting the exact same packets from OwnTone and then it's really strange.

One (Yamaha R-N301) is Airplay 1, the other (Ikea Sonos speaker) is Airplay 2.

I haven't tried it with regular audio yet, will report back once I do. 

```json
{ "outputs": [ { "id": "202481593033816", "name": "Bedroom", "type": "AirPlay 1", "selected": false, "has_password": false, "requires_auth": false, "needs_auth_key": false, "volume": 50, "format": "alac", "supported_formats": [ "alac" ] }, { "id": "61856313623102", "name": "Kitchen", "type": "AirPlay 1", "selected": true, "has_password": false, "requires_auth": false, "needs_auth_key": false, "volume": 44, "format": "alac", "supported_formats": [ "alac" ] }, { "id": "33081262955074", "name": "mbp", "type": "AirPlay 1", "selected": false, "has_password": false, "requires_auth": true, "needs_auth_key": true, "volume": 50, "format": "alac", "supported_formats": [ "alac" ] }, { "id": "690932181033", "name": "R-N301", "type": "AirPlay 1", "selected": true, "has_password": false, "requires_auth": false, "needs_auth_key": false, "volume": 67, "format": "alac", "supported_formats": [ "alac" ] }, { "id": "0", "name": "Computer", "type": "ALSA", "selected": false, "has_password": false, "requires_auth": false, "needs_auth_key": false, "volume": 50, "format": "pcm", "supported_formats": [ "pcm" ] } ] }
```

**Comment by ejurgensen** [comment]
@gearhead somehow you don't have the current version of at least the web UI interface. The offset settings would be on the screen you posted, you would find them easily. Maybe you didn't run "sudo make install"? That will normally install the web UI files, along with the binary itself.

**Comment by ejurgensen** [comment]
Btw, I retried with the radio station you linked to, but still couldn't reproduce the issue. I will try with Airplay 1 + 2 combo to see if @ErikFontanel's situation reproduces.

**Comment by gearhead** [comment]
> [@gearhead](https://github.com/gearhead) somehow you don't have the current version of at least the web UI interface. The offset settings would be on the screen you posted, you would find them easily. Maybe you didn't run "sudo make install"? That will normally install the web UI files, along with the binary itself.

I found it. I re-built the package and reinstalled it. I now see the timing offsets on 'http://localhost:3689/#/settings/devices'. I will play with these later today and report back. I am running the version: g0f2133e2 from 'master' which has your commits form Jan 5 2026.

**Comment by ejurgensen** [comment]
Just ended a longer radio playback session with the Airplay 1 and 2 combo, and did not see a sync issue. Without a way of reproducing the issue, I will have to close it.

**Comment by gearhead** [comment]
I never heard a sync issue between any remote outputs. It was only with the local output compared to the remote ones. The remotes have always been in sync with each other. It is still early here and I will have time today to do a longer test and see what I hear with the local compared to a shairport-sync remote output now that we can adjust the timing offset. I did try a bit and it sounds like, with 0 offset, that the local alsa output is ahead of the remove shairport-sync. I need to adjust it to sync the signal then let it play a while and see if it drifts. Will do so today and let you know.

**Comment by gearhead** [comment]
Well, I was able to do a bit of investigation and I think I may not be doing it correctly. Do I need to restart owntone every time to get the time offsets to 'take'? Is it enough to turn off then on the output on http://localhost:3689/#/settings/devices? I put the webradio in as 'add stream' on http://localhost:3689/#/ and hit play then started and stopped it here. I made a change to the timing then stop/start play of the webradio. I was never was able to get a time offset which would sync the local alsa output to the remote shairport-sync. The local alsa was always ahead of the shairport-sync. There was no amount of adjustment of the local alsa or the remote timing that could bring them into sync. I assume that - numbers are ahead in timing and + numbers are behind. I did test with '0' offset and 2 separate shairport-sync remote speakers and these were in sync as best I can tell with no adjustment necessary. It is the local alsa is always ahead of the shairport-sync. Since it was never in sync in my test, I did not play it longer term to see if it drifts out.

**Comment by ejurgensen** [comment]
It sounds like you did it correctly, but encountered an issue that I have just fixed, where the setting wouldn't be applied if you start playback again shortly after having paused it. See [my comment here](https://github.com/owntone/owntone-server/pull/1955#issuecomment-3716357210).

So you can either pull from the master branch, build and try again (but make sure to change the offset during pause, not during playback), _or_ using your current version you can do like this: Pause playback, change the setting, wait minimum 10 secs, start playback again.

A positive value is a delay like you assumed, but unfortunately there was a bug where it was the opposite for Airplay. I have also fixed that. But for your test, I suggest just changing the ALSA device. And since it is ahead, you would need to set a positive value to delay it. Try setting 500 first, just to make sure the delay is working.

**Comment by gearhead** [comment]
OK. I think I finally get it. I am at -165 on the alsa output and both my son and I think it is synced. I'll let it play for a while and see how it goes. What value did you end up at to get it synced? 
Now, will this stick through a reboot, or do I need to code it in every time I enable the output? 
```
# curl -X GET "http://localhost:3689/api/outputs/{1}"
{ "id": "1", "name": "Soundcard: HiFiBerry DAC+ Pro", "type": "ALSA", "selected": true, "has_password": false, "requires_auth": false, "needs_auth_key": false, "volume": 22, "offset_ms": -165, "format": "pcm", "supported_formats": [ "pcm" ] }
```
And while I am asking about API stuff, I have tried this command to set a pin for an airplay2 output and it does not seem to work so I guess I am not sending the correct info...
```
# curl -X PUT "http://localhost:3689/api/outputs/{235118494339028}" --data "{\"selected\":true, \"pin\":4448}"
<html>
<head>
<title>400 Bad Request</title>
</head>
<body>
<h1>Bad Request</h1>
</body>
</html>
```

**Comment by ejurgensen** [comment]
> What value did you end up at to get it synced? Now, will this stick through a reboot, or do I need to code it in every time I enable the output?

My RPi4 is in sync with a value of 0, but note I just use the built-in sound jack when testing. Your Hifiberry may be adding those 165 ms. The value should certainly be saved over a reboot. Internally it’s a speaker attribute just like volume.

The PIN you submit via the API is for Airplay pairing. It will only work if the device is in pairing mode (i.e. displaying a PIN). If you have set a PIN in the speaker config, then you give it to OwnTone via the config file, so not the API.

**Comment by gearhead** [comment]
THanks for doing this. It seems to be reliable and consistent, now, with regard to sync once it is set. 

Is there another method other than 'stop, change offset, wait 10s, restart' that we can we use to set the offset? We are playing the music via a fifo pipe into owntone from MPD and I do not interface with the UI to stop playback. I was able to get it set appropriately. by using the UI to do so, but am wondering how we may be able to do it otherwise via the API  or via config?
```

# mpc outputs
Output 4 (owntone) is enabled
	allowed_formats=""
	dop="0"

# aplay -L | grep owntone
owntonempdfifo
    pcm output device to pipe mpd output to an owntone fifo pipe with rate conversion (S16_LE, 44.1kHz)
owntonempdFIFO
    pcm output device to pipe mpd output to an owntone fifo pipe without rate conversion
```
I know this is a bit convoluted, but we have a common UI for all inputs and are using owntone to be able to be able to do this as a muitl-room setup...

**Comment by ejurgensen** [comment]
> It seems to be reliable and consistent, now, with regard to sync once it is set.

So is the drift issue gone? That's surprising and maybe even a bit worrying, because then I really don't understand what's going on.

> Is there another method other than 'stop, change offset, wait 10s, restart' that we can we use to set the offset?

Well the 10s is fixed, so that part doesn't apply with trunk. But you still need to pause playback before making the change. The change can also be done via the json api, see [this](https://owntone.github.io/owntone-server/json-api/#change-an-output).

I'm a curious what the solution you describe consists of, would you mind sharing some details on it? I'm also curious why you are running MPD on top, since OwnTone has mpd built-in. Maybe using some part MPD that OwnTone doesn't support?

**Comment by gearhead** [comment]
Well, I tried again with a long playing time. it is slightly out of time, but that may be because I do not have it exactly right with my offset. I am not completely sure. I do not think it is as far out as it was previously. I will need to perform another test and see. 

I am guessing I can put the offset in the /etc/owntone.conf for the  individual outputs? I am aware of the api method as well.

Our 'solution'... That is a long one. We have been using RuneAudio as a basis for all the work we have done to date. We have built the needed packages and extended the 2014 capabilities and brought it up to date with the more current OS. I see that owntone has MPD built in. We use the pre-packaged MPD from RPiOS, so maybe we can use the one built into Owntone, but I'll have to try and see if it will work.

**Comment by ejurgensen** [comment]
> I am guessing I can put the offset in the /etc/owntone.conf for the individual outputs?

Yes, but only for local audio and Chromecast, not Airplay. I was thinking for deprecating those settings since it's now possible in the web UI, but I can keep them around.

I will close the issue since it seems to have improved, and anyway isn't possible for me to reproduce.

**Comment by gearhead** [comment]
I know this is closed, but wanted to post once more to document it. 
This still happens where the Local gets out of sync to the airplay output. I have RPi 3B+ with a hifiberry card for its local output. If I set the offset on the local alsa output to -170ms, it is ~in sync when play starts. If I let it play a while, I eventually can detect that the local output gets ahead of the airplay stream as compared to on another RPi (Pi4 or Pi2). Can I send you a hifiberry or other RPi i2s card? Basically, anything like this: [Waveshare DAC](https://www.electrokit.com/en/pcm5122-hifi-dac-32-bit-i2c-for-raspberry-pi)

The offset will allow it to start synchronized, but over time it drifts to be ahead of the airplay stream.

**Comment by ejurgensen** [comment]
I suppose it's not so surprising the issue is still there. How long does it typically take before you notice the issue?

I can't promise you I can solve the issue, but I don't mind giving it a go. You can send me an email at espenjurgensen@gmail.com and I'll share my address.

**Comment by gearhead** [comment]
So, after about 30 minutes of playing it gets enough out of sync that I can hear it. 
I guess another possibility may be to have owntone use either the local alsa output or for it to use a local shairport-sync output if it is available. My guess is that this may stay in sync, but I do not know. Like I said before, we have MPD running as the frontend and providing a fifo pipe to owntone and this gets out of sync. I have also tested it using the Owntone UI and 'adding a stream' to the queue. Same result: out of sync over time. Starts in sync with an offset of ~-170 on the alsa output then drifts. 
  
You are in denmark, right? I was looking online and it looks like I can purchase online for about US $25.00 and have it shipped directly to you from europe versus shipping it from here in the US. I'd have to see how much that'd be to ship one from here as I have a few on hand that I could let go of pretty easily. Let me see what it would be to ship one from here to DK.

**Comment by gearhead** [comment]
Well, I am back at this after a delay. This problem seems to have gone away.  I have been listening all day and the sync has remained constant. One thing that I did address in the meantime was a DNSSEC problem on the Pi. I had DNSSEC enabled and it may not have synced to ntp at boot. It is possible that one or the other Pi was was not synced to ntp and now it is. Could that be the source of the drift as the clock of the Pi drifts away from being synced? As it is, once the ms offset is set for that particular output, sync seems to stay where it is, at least today.

**Comment by ejurgensen** [comment]
Just now, I also tried a longer playback session with a radio station, and my RPi with the new i2s played nicely in sync with Airplay. I didn't need to set an offset.

I suppose the cause of your initial observation isn't quite fixed, but I will close this issue as it probably won't be possible to find it. I don't know if DNSSEC could have something to do with it.

**Comment by gearhead** [comment]
If I understand the timing aspect of airplay, it relies on the clocks of all networked devices to be synced to ntp. Do I have that right? My logic is: the RPi doesn't have a rtc and at boot it tries to sync its clock with an ntp server by name. If DNSSEC is enabled, it tries to sync, the name lookup fails and it never syncs its clock.  I discovered this with another web radio station. It wouldn't look up due to a failed DNSSEC because of a time sync issue. Once I fixed the DNSSEC issue, time sync was confirmed , I could connect with that web radio again. I hope this was also the reason that over time my RPi would drift out of sync with others because their clocks were not able to sync to ntp...

**Comment by ejurgensen** [comment]
That's not quite how it works. AirPlay doesn't care about true time, and the time does not come from a real ntp server. Instead, the sender acts as ntp server and whatever he thinks the time is is what the speakers will use.

**Comment by gearhead** [comment]
So, if one or more of the pis is not synced to ntp, basically making sure it's clock doesn't drift .If it isn't synced and it's time drifts, they could get out of time sync with each other and could this be why it gets out of music sync.
